### ISSUE TITLE
Normalize the names of states & provinces for various objects

### ISSUE THREAD

**Issue by ccaputo** [peeringdb/peeringdb#1079]
Not sure how this would work, but it would be good if there was a way to have state names and province names be normalized to either their short-form or their long-form names, with consistency across a country. As an example, the bulk of the following search results are by short-form, while some are not. A good motivation for doing this to is increase the effectiveness for a search for a given object type, without needing to search by both short-form and long-form. An alternative solution might be to make it so searches automatically include results for both the short-form and long-form names, but that does not help with data exported for later review, such as by the available JSON or CSV download mechanisms, since subsequent offline searches will be forced to consider both.

Sensitivity to the general philosophy of not changing a user's record without permission, should be considered as part of this. It may be that existing records get corrected via assistance by the Admin Committee interacting with users, while new changes are limited to a desired format.

https://www.peeringdb.com/advanced_search?country__in=CA&reftag=fac

and

https://www.peeringdb.com/advanced_search?country__in=US&reftag=fac

<img width="117" alt="Screen Shot 2021-10-29 at 3 37 28 PM" src="https://user-images.githubusercontent.com/1417833/139508562-b5301d05-3175-43bb-844f-652f0a28c64b.png">

<img width="71" alt="Screen Shot 2021-10-29 at 3 38 59 PM" src="https://user-images.githubusercontent.com/1417833/139508669-477f0d90-a459-4bba-9cfe-8b25f1dccfc0.png">

**Comment by ccaputo** [comment]
Related: #777

**Comment by arnoldnipper** [comment]
The current address tool provides a consistent format. The normalisation of addresses is a never-ending story and is not the silver bullet for searching.

**Comment by ynbrthr** [comment]
+1, let's do that

**Comment by ynbrthr** [comment]
PC, can I get some +1s?

**Comment by martinhannigan** [comment]
Agree with Chris in data mods

Feels like a low 2022 roadmap priority = accuracy, % impact

+1

**Comment by mcmanuss8** [comment]
+1 we should normalize states/provinces and countries. I see no downside.

**Comment by vegu** [comment]
**summary**

- Implement and run a version of address normalization tool that only normalizes state and province information, other address data should be left alone

To clarify: countries are already normalized through a database relationship

**Comment by ynbrthr** [comment]
does that address being to search on both two-letter abbreviations and full
names? or would we need a separate issue for that?

**Comment by vegu** [comment]
@ynbrthr this can be done within the scope of this ticket

**Comment by ccaputo** [comment]
On beta, running `pdb-container pdb_geo_normalize_existing --state-only fac` (run time was `real    2m49.698s`) results in a ton of:

```
/srv/www.peeringdb.com/venv/lib/python3.9/site-packages/django/core/cache/backends/base.py:250: CacheKeyWarning: Cache key contains characters that will cause errors if used with memcached: 'geo.normalize.state.ID.Sumatera Barat'                                                                                                                                 
  warnings.warn(warning, CacheKeyWarning)                                                                                                                                                                                                                                                                                                                             
/srv/www.peeringdb.com/venv/lib/python3.9/site-packages/django/core/cache/backends/base.py:250: CacheKeyWarning: Cache key contains characters that will cause errors if used with memcached: ':1:geo.normalize.state.ID.Sumatera Barat'                                                                                                                              
  warnings.warn(warning, CacheKeyWarning)                                                                                                                                                                                                                                                                                                                             
/srv/www.peeringdb.com/venv/lib/python3.9/site-packages/django/core/cache/backends/base.py:250: CacheKeyWarning: Cache key contains characters that will cause errors if used with memcached: 'geo.normalize.state.GB.Co. Durham'                                                                                                                                     
  warnings.warn(warning, CacheKeyWarning)                                                                                                                                                                                                                                                                                                                             
/srv/www.peeringdb.com/venv/lib/python3.9/site-packages/django/core/cache/backends/base.py:250: CacheKeyWarning: Cache key contains characters that will cause errors if used with memcached: ':1:geo.normalize.state.GB.Co. Durham'                                                                                                                                  
  warnings.warn(warning, CacheKeyWarning)                                                                                                                                                                                                                                                                                                                             
```

Those should be handled. Same thing happens with `org`.

Also, when the Melissa credits run out and are renewed, there is a timeout, and these happen:

```
Traceback (most recent call last):                                                                                                                                                                                                                                                                                                                                    
  File "/srv/www.peeringdb.com/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 449, in _make_request                                                                                                                                                                                                                                                
    six.raise_from(e, None)                                                                                                                                                                                                                                                                                                                                           
  File "<string>", line 3, in raise_from                                                                                                                                                                                                                                                                                                                              
  File "/srv/www.peeringdb.com/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 444, in _make_request                                                                                                                                                                                                                                                
    httplib_response = conn.getresponse()                                                                                                                                                                                                                                                                                                                             
  File "/usr/local/lib/python3.9/http/client.py", line 1377, in getresponse                                                                                                                                                                                                                                                                                           
    response.begin()                                                                                                                                                                                                                                                                                                                                                  
  File "/usr/local/lib/python3.9/http/client.py", line 320, in begin                                                                                                                                                                                                                                                                                                  
    version, status, reason = self._read_status()                                                                                                                                                                                                                                                                                                                     
  File "/usr/local/lib/python3.9/http/client.py", line 281, in _read_status                                                                                                                                                                                                                                                                                           
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")                                                                                                                                                                                                                                                                                                          
  File "/usr/local/lib/python3.9/socket.py", line 704, in readinto                                                                                                                                                                                                                                                                                                    
    return self._sock.recv_into(b)                                                                                                                                                                                                                                                                                                                                    
  File "/usr/local/lib/python3.9/ssl.py", line 1241, in recv_into                                                                                                                                                                                                                                                                                                     
    return self.read(nbytes, buffer)                                                                                                                                                                                                                                                                                                                                  
  File "/usr/local/lib/python3.9/ssl.py", line 1099, in read                                                                                                                                                                                                                                                                                                          
    return self._sslobj.read(len, buffer)                                                                                                                                                                                                                                                                                                                             
socket.timeout: The read operation timed out                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                      
During handling of the above exception, another exception occurred:                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                      
Traceback (most recent call last):                                                                                                                                                                                                                                                                                                                                    
  File "/srv/www.peeringdb.com/venv/lib/python3.9/site-packages/requests/adapters.py", line 440, in send                                                                                                                                                                                                                                                              
    resp = conn.urlopen(                                                                                                                                                                                                                                                                                                                                              
  File "/srv/www.peeringdb.com/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 785, in urlopen                                                                                                                                                                                                                                                      
    retries = retries.increment(                                                                                                                                                                                                                                                                                                                                      
  File "/srv/www.peeringdb.com/venv/lib/python3.9/site-packages/urllib3/util/retry.py", line 550, in increment                                                                                                                                                                                                                                                        
    raise six.reraise(type(error), error, _stacktrace)                                                                                                                                                                                                                                                                                                                
  File "/srv/www.peeringdb.com/venv/lib/python3.9/site-packages/urllib3/packages/six.py", line 770, in reraise                                                                                                                                                                                                                                                        
    raise value                                                                                                                                                                                                                                                                                                                                                       
  File "/srv/www.peeringdb.com/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen                                                                                                                                                                                                                                                      
    httplib_response = self._make_request(                                                                                                                                                                                                                                                                                                                            
  File "/srv/www.peeringdb.com/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 451, in _make_request                                                                                                                                                                                                                                                
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)                                                                                                                                                                                                                                                                                                   
  File "/srv/www.peeringdb.com/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout                                                                                                                                                                                                                                               
    raise ReadTimeoutError(                                                                                                                                                                                                                                                                                                                                           
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='address.melissadata.net', port=443): Read timed out. (read timeout=5)                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                      
During handling of the above exception, another exception occurred:                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                      
Traceback (most recent call last):                                                                                                                                                                                                                                                                                                                                    
  File "/srv/www.peeringdb.com/peeringdb_server/geo.py", line 226, in global_address                                                                                                                                                                                                                                                                                  
    response = requests.get(                                                                                                                                                                                                                                                                                                                                          
  File "/srv/www.peeringdb.com/venv/lib/python3.9/site-packages/requests/api.py", line 75, in get                                                                                                                                                                                                                                                                     
    return request('get', url, params=params, **kwargs)                                                                                                                                                                                                                                                                                                               
  File "/srv/www.peeringdb.com/venv/lib/python3.9/site-packages/requests/api.py", line 61, in request                                                                                                                                                                                                                                                                 
    return session.request(method=method, url=url, **kwargs)                                                                                                                                                                                                                                                                                                          
  File "/srv/www.peeringdb.com/venv/lib/python3.9/site-packages/requests/sessions.py", line 529, in request                                                                                                                                                                                                                                                           
    resp = self.send(prep, **send_kwargs)                                                                                                                                                                                                                                                                                                                             
  File "/srv/www.peeringdb.com/venv/lib/python3.9/site-packages/requests/sessions.py", line 645, in send                                                                                                                                                                                                                                                              
    r = adapter.send(request, **kwargs)                                                                                                                                                                                                                                                                                                                               
  File "/srv/www.peeringdb.com/venv/lib/python3.9/site-packages/requests/adapters.py", line 532, in send                                                                                                                                                                                                                                                              
    raise ReadTimeout(e, request=request)                                                                                                                                                                                                                                                                                                                             
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='address.melissadata.net', port=443): Read timed out. (read timeout=5)                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                      
During handling of the above exception, another exception occurred:                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                      
Traceback (most recent call last):                                                                                                                                                                                                                                                                                                                                    
  File "/srv/www.peeringdb.com/./manage.py", line 10, in <module>                                                                                                                                                                                                                                                                                                     
    execute_from_command_line(sys.argv)                                                                                                                                                                                                                                                                                                                               
  File "/srv/www.peeringdb.com/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line                                                                                                                                                                                                                           
    utility.execute()                                                                                                                                                                                                                                                                                                                                                 
  File "/srv/www.peeringdb.com/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute                                                                                                                                                                                                                                             
    self.fetch_command(subcommand).run_from_argv(self.argv)                                                                                                                                                                                                                                                                                                           
  File "/srv/www.peeringdb.com/venv/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv                                                                                                                                                                                                                                           
    self.execute(*args, **cmd_options)                                                                                                                                                                                                                                                                                                                                
  File "/srv/www.peeringdb.com/venv/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute                                                                                                                                                                                                                                                 
    output = self.handle(*args, **options)                                                                                                                                                                                                                                                                                                                            
  File "/srv/www.peeringdb.com/peeringdb_server/management/commands/pdb_geo_normalize_existing.py", line 99, in handle                                                                                                                                                                                                                                                
    output_list = self.normalize(reftag, _id, limit=limit)                                                                                                                                                                                                                                                                                                            
  File "/srv/www.peeringdb.com/venv/lib/python3.9/site-packages/reversion/revisions.py", line 324, in do_revision_context                                                                                                                                                                                                                                             
    return func(*args, **kwargs)                                                                                                                                                                                                                                                                                                                                      
  File "/usr/local/lib/python3.9/contextlib.py", line 79, in inner                                                                                                                                                                                                                                                                                                    
    return func(*args, **kwds)                                                                                                                                                                                                                                                                                                                                        
  File "/srv/www.peeringdb.com/peeringdb_server/management/commands/pdb_geo_normalize_existing.py", line 205, in normalize                                                                                                                                                                                                                                            
    self._normalize_state(entity, output_dict, self.commit)                                                                                                                                                                                                                                                                                                           
  File "/srv/www.peeringdb.com/peeringdb_server/management/commands/pdb_geo_normalize_existing.py", line 256, in _normalize_state                                                                                                                                                                                                                                     
    normalized_state = self.melissa.normalize_state(                                                                                                                                                                                                                                                                                                                  
  File "/srv/www.peeringdb.com/peeringdb_server/geo.py", line 275, in normalize_state                                                                                                                                                                                                                                                                                 
    result = self.global_address(country=country_code, address1=state)                                                                                                                                                                                                                                                                                                
  File "/srv/www.peeringdb.com/peeringdb_server/geo.py", line 233, in global_address                                                                                                                                                                                                                                                                                  
    raise Timeout()                                                                                                                                                                                                                                                                                                                                                   
peeringdb_server.geo.Timeout: Geo location lookup has timed out                                                                                                                                                                                                                                                                                                       
```

and the process quits. These need to retry/continue or have a checkpoint/restart mechanism, because otherwise we completely waste the effort of the run and end up paying for more Melissa credits without actually completing. The `org` sweep is unable to finish because of this and some money has been wasted. Maybe a checkpointing and continue method of some type is needed. Not sure how to solve this and let me know if I am being unclear.

Additionally, if we ever do complete a clean-up run, we need to prevent users from re-causing the problem, by disallowing the re-entering of unnormalized data. Otherwise this script would need to be run routinely, and its use of Melissa makes that too costly to consider.

Some $200 in Melissa charges was spent today in this testing, so this is pretty serious. We need a better solution.

**Comment by peterhelmenstine** [comment]
Ooof that's bad. +1

**Comment by ccaputo** [comment]
Ran some tests and things are looking good. I notice the log entries, ex:

```
timestamp='2022-04-19T23:00:23.721928Z' level='info' event='MELISSA' logger='peeringdb_server.geo' url='https://address.melissadata.net/v3/WEB/GlobalAddress/doGlobalAddress'
```

@vegu would it make sense to include what is being queried in those log entries? Right now visibility is just into the number of queries and when.

Aside to folks who run `pdb_geo_normalize_existing`, it is a good idea to run `tail -f [logdir]/django.log` when doing so. That said, since it runs in a container, I believe killing an out of control run requires killing the docker instance.

**Comment by vegu** [comment]
@ccaputo user triggered melissa requests (e.g., through fac / org saves and some api queries) will also log the source of the request so we can co-relate where in our ecosystem it is coming from. That said, i could see some use in logging actual payload sent to melissa as well.
