### ISSUE TITLE
HTTP 404 for dom-purify/purify.min.js.map and showdown/showdown.min.js.map

### ISSUE THREAD

**Issue by ccaputo** [peeringdb/peeringdb#1149]
Production 2.35.0 and Beta 2.36.0-beta2 both have this problem:

```
DevTools failed to load source map: Could not load content for https://www.peeringdb.com/s/2.35.0/dom-purify/purify.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://www.peeringdb.com/s/2.35.0/showdown/showdown.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

```
DevTools failed to load source map: Could not load content for https://beta.peeringdb.com/s/2.36.0-beta2/dom-purify/purify.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://beta.peeringdb.com/s/2.36.0-beta2/showdown/showdown.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

A quick check of access.log's shows these clients affected:

```
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36" 0.000
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4590.2 Safari/537.36 Chrome-Lighthouse" 0.000
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36" 0.000
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36" 0.000
"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36" 0.000
```

I suspect the solution is to remove these lines from the related minified javascript libraries:

`//# sourceMappingURL=purify.min.js.map`
`//# sourceMappingURL=showdown.min.js.map`

**Comment by arnoldnipper** [comment]
@vegu, please confirm

**Comment by leovegoda** [comment]
@ccaputo Can this be closed?

**Comment by ccaputo** [comment]
> @ccaputo Can this be closed?

Chrome browser console still reveals the following, so the problem continues:

```
DevTools failed to load source map: Could not load content for https://www.peeringdb.com/s/2.40.0/showdown/showdown.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://www.peeringdb.com/s/2.40.0/dom-purify/purify.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE```

**Comment by ccaputo** [comment]
With Chrome 105.0.5195.125, https://beta.peeringdb.com/ produces:

```
Error in event handler: TypeError: Cannot read properties of undefined (reading 'length')
    at cosmeticFilters (chrome-extension://epcnnfbjfcgphgdmggkamkmgojdagdnn/js/contentscript-start.js:108:24)
    at filteringHandler (chrome-extension://epcnnfbjfcgphgdmggkamkmgojdagdnn/js/contentscript-start.js:136:13)
    at messagingConnector (chrome-extension://epcnnfbjfcgphgdmggkamkmgojdagdnn/js/vapi-client.js:177:9)
DevTools failed to load source map: Could not load content for https://beta.peeringdb.com/s/2.41.0-beta/showdown/showdown.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

No idea what the first JS error is about - and that should be addressed too - but I can see that while https://beta.peeringdb.com/s/2.41.0-beta/showdown.min.js.map works, https://beta.peeringdb.com/s/2.41.0-beta/showdown/showdown.min.js.map (note extra 'showdown') fails to load, per the access.log a command-R refresh results in:

```
[12/Oct/2022:14:39:06 +0000] "GET /jsi18n/ HTTP/1.1" 200 1050 "https://beta.peeringdb.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36" 0.012
[12/Oct/2022:14:39:06 +0000] "GET /s/2.41.0-beta/20c/twentyc.edit.js HTTP/1.1" 200 7231 "https://beta.peeringdb.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36" 0.000
[12/Oct/2022:14:39:06 +0000] "GET /s/2.41.0-beta/20c/twentyc.sortable.js HTTP/1.1" 200 688 "https://beta.peeringdb.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36" 0.000
[12/Oct/2022:14:39:06 +0000] "GET /s/2.41.0-beta/bootstrap/css/bootstrap.css HTTP/1.1" 200 29380 "https://beta.peeringdb.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36" 0.000
[12/Oct/2022:14:39:06 +0000] "GET /s/2.41.0-beta/bootstrap/css/bootstrap.css.map HTTP/1.1" 200 389228 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36" 0.002
[12/Oct/2022:14:39:06 +0000] "GET /s/2.41.0-beta/bootstrap/js/bootstrap.bundle.min.js HTTP/1.1" 200 27159 "https://beta.peeringdb.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36" 0.000
[12/Oct/2022:14:39:06 +0000] "GET /s/2.41.0-beta/django-security-keys/django-security-keys.js HTTP/1.1" 200 3010 "https://beta.peeringdb.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36" 0.000
[12/Oct/2022:14:39:06 +0000] "GET /s/2.41.0-beta/dom-purify/purify.min.js HTTP/1.1" 200 9049 "https://beta.peeringdb.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36" 0.000
[12/Oct/2022:14:39:06 +0000] "GET /s/2.41.0-beta/hamburger-colorful.png HTTP/1.1" 200 387 "https://beta.peeringdb.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36" 0.000
[12/Oct/2022:14:39:06 +0000] "GET /s/2.41.0-beta/jquery/jquery.js HTTP/1.1" 200 36059 "https://beta.peeringdb.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36" 0.000
[12/Oct/2022:14:39:06 +0000] "GET /s/2.41.0-beta/site.css HTTP/1.1" 200 6844 "https://beta.peeringdb.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36" 0.000
[12/Oct/2022:14:39:07 +0000] "GET /s/2.41.0-beta//social-facebook.png HTTP/1.1" 200 10269 "https://beta.peeringdb.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36" 0.000
[12/Oct/2022:14:39:07 +0000] "GET /s/2.41.0-beta//social-linkedin.png HTTP/1.1" 200 16516 "https://beta.peeringdb.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36" 0.000
[12/Oct/2022:14:39:07 +0000] "GET /s/2.41.0-beta//social-youtube.png HTTP/1.1" 200 2448 "https://beta.peeringdb.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36" 0.000
[12/Oct/2022:14:39:07 +0000] "GET /s/2.41.0-beta/showdown/showdown.min.js.map HTTP/1.1" 404 181 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36" 0.000
```

**Comment by ccaputo** [comment]
@vegu, any thoughts on the:

```
Error in event handler: TypeError: Cannot read properties of undefined (reading 'length')
```

?

**Comment by grizz** [comment]
@ccaputo  We weren't able to reproduce that, so will check again once this is deployed to beta.

**Comment by ccaputo** [comment]
> @ccaputo We weren't able to reproduce that, so will check again once this is deployed to beta.

Ahh - sorry to waste your time. I see it relates to a Chrome extension so I suspect you needn't bother. (I tested in an incognito window and the console error didn't happen.)

**Comment by grizz** [comment]
All good, thanks.
