### ISSUE TITLE
Reset IX-F suggestions link non-functional

### ISSUE THREAD

**Issue by vegu** [peeringdb/peeringdb#1253]
**Describe the bug**
Click `Reset suggestions` link currently does nothing.

![image](https://user-images.githubusercontent.com/143124/192249655-da3de940-cae1-4d87-9da6-975e0c1d2a6f.png)

Javascript console reveals the error to be a typo in a variable name

```
Uncaught ReferenceError: PeerignDB is not defined
    at IXFProposals.reset_proposals (peeringdb.js:18:391)
    at HTMLAnchorElement.<anonymous> (peeringdb.js:17:285)
    at HTMLAnchorElement.dispatch (jquery.js:2:43064)
    at v.handle (jquery.js:2:41048)
```

**Comment by arnoldnipper** [comment]
Routed through to 3a as identified as a bug by a developer
