### ISSUE TITLE
pdb sync issues

### ISSUE THREAD

**Issue by grizz** [peeringdb/peeringdb#24]
```
Operations to perform:
  Synchronize unmigrated apps: django_peeringdb
  Apply all migrations: admin, contenttypes, auth, sessions
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  No migrations to apply.
Starting new HTTPS connection (1): www.peeringdb.com
"GET /api/org?since=1469134856 HTTP/1.1" 200 None
org last update 1469134856 0 changed
data to be processed 0
Starting new HTTPS connection (1): www.peeringdb.com
"GET /api/fac?since=1469134856 HTTP/1.1" 200 None
fac last update 1469134856 0 changed
data to be processed 0
Starting new HTTPS connection (1): www.peeringdb.com
"GET /api/net?since=1469131373 HTTP/1.1" 200 None
net last update 1469131373 4 changed
data to be processed 4
Traceback (most recent call last):
  File "$PATH/pdbvenv/bin/peeringdb", line 9, in <module>
    load_entry_point('peeringdb==0.4.4.1', 'console_scripts', 'peeringdb')()
  File "$PATH/pdbvenv/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "$PATH/pdbvenv/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "$PATH/pdbvenv/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "$PATH/pdbvenv/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "$PATH/pdbvenv/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "$PATH/pdbvenv/lib/python2.7/site-packages/peeringdb/cli.py", line 167, in sync
    db.sync()
  File "$PATH/pdbvenv/lib/python2.7/site-packages/peeringdb/localdb.py", line 140, in sync
    call_command('pdb_sync', interactive=False)
  File "$PATH/pdbvenv/lib/python2.7/site-packages/django/core/management/__init__.py", line 120, in call_command
    return command.execute(*args, **defaults)
  File "$PATH/pdbvenv/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "$PATH/pdbvenv/lib/python2.7/site-packages/django_peeringdb/management/commands/pdb_sync.py", line 85, in handle
    self.sync(tables)
  File "$PATH/pdbvenv/lib/python2.7/site-packages/django_peeringdb/management/commands/pdb_sync.py", line 92, in sync
    self.update_db(cls, self.get_objs(cls))
  File "$PATH/pdbvenv/lib/python2.7/site-packages/django_peeringdb/management/commands/pdb_sync.py", line 127, in update_db
    sync.sync_obj(cls, row)
  File "$PATH/pdbvenv/lib/python2.7/site-packages/django_peeringdb/sync.py", line 25, in sync_obj
    obj.full_clean()
  File "$PATH/pdbvenv/lib/python2.7/site-packages/django/db/models/base.py", line 1171, in full_clean
    raise ValidationError(errors)
django.core.exceptions.ValidationError: {'name': [u'Network with this Name already exists.']}
```

[peeringdb.sqlite3.20160721.has_error.zip](https://github.com/peeringdb/peeringdb/files/377572/peeringdb.sqlite3.20160721.has_error.zip)

**Comment by vegu** [comment]
fixed, was caused by bad data server-side, refer to #32 for more info on the issue and future plans to avoid it
