### ISSUE TITLE
Full database sync is failing

### ISSUE THREAD

**Issue by bcavns01** [peeringdb/peeringdb#574]
```This is partially a request for help and partially to notify the peering db team that there seems to be a persistent db data issue.

We do nightly syncs, full syncs where we purge the DB and do a full re-sync as previously suggested by one of the peeringdb python client contributors.  However, even the full sync seems to be failing now.

We've been trying to sync multiple times for the past 24 hours and continue to get an error for a non-existent facility as seen below:

https://www.peeringdb.com:443 "GET /api/netfac?since=0&limit=0 HTTP/1.1" 200 6103570
netfac last update 0 26951 changed
data to be processed 26951
{'fac': [u'facility instance with id 602 does not exist.']} : errors: {'fac': [u'facility instance with id 602 does not exist.']}
fac: Missing Object, dict: {'_validators': [], 'auto_created': False, 'serialize': True, 'cached_col': Col(peeringdb_network_facility, django_peeringdb.NetworkFacility.fac), '_unique': False, 'unique_for_year': None, 'blank': False, 'help_text': u'', 'null': False, 'to_fields': ['id'], 'db_index': True, 'is_relation': True, 'unique_for_month': None, 'unique_for_date': None, 'primary_key': False, 'concrete': True, 'swappable': True, 'remote_field': <ManyToOneRel: django_peeringdb.networkfacility>, 'max_length': None, 'db_tablespace': u'', 'from_fields': [u'self'], 'verbose_name': u'fac', '_get_default': <function <lambda> at 0x7f9f8b6d9758>, 'creation_counter': 96, 'validators': [], 'editable': True, 'related_model': <class 'django_peeringdb.models.concrete.Facility'>, 'error_messages': {u'unique': u'%(model_name)s with this %(field_label)s already exists.', u'invalid': u'%(model)s instance with %(field)s %(value)r does not exist.', u'invalid_choice': u'Value %(value)r is not a valid choice.', u'blank': u'This field cannot be blank.', u'null': u'This field cannot be null.', u'unique_for_date': u'%(field_label)s must be unique for %(date_field_label)s %(lookup_type)s.'}, '_related_fields': [(<django.db.models.fields.related.ForeignKey: fac>, <django.db.models.fields.AutoField: id>)], '_error_messages': None, 'db_constraint': True, '_verbose_name': None, 'name': 'fac', 'db_column': None, 'default': 0, 'choices': [], 'column': u'fac_id', 'model': <class 'django_peeringdb.models.concrete.NetworkFacility'>, 'attname': u'fac_id', 'opts': <Options for NetworkFacility>}
fac.602 not found locally, trying to fetch object...
Starting new HTTPS connection (1): www.peeringdb.com
https://www.peeringdb.com:443 "GET /api/fac/602?depth=0 HTTP/1.1" 404 33
Traceback (most recent call last):
  File "/usr/local/bin/peeringdb", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/peeringdb/cli.py", line 164, in sync
    db.sync()
  File "/usr/local/lib/python2.7/dist-packages/peeringdb/localdb.py", line 124, in sync
    call_command('pdb_sync', interactive=False)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 131, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django_peeringdb/management/commands/pdb_sync.py", line 91, in handle
    self.sync(tables, pk, limit=limit)
  File "/usr/local/lib/python2.7/dist-packages/django_peeringdb/management/commands/pdb_sync.py", line 98, in sync
    self.update_db(cls, self.get_objs(cls, pk=pk, **kwargs))
  File "/usr/local/lib/python2.7/dist-packages/django_peeringdb/management/commands/pdb_sync.py", line 180, in update_db
    self._sync(cls, row)
  File "/usr/local/lib/python2.7/dist-packages/django_peeringdb/management/commands/pdb_sync.py", line 164, in _sync
    r = self.rpc.get(field, int(m.group(1)), depth=0)
  File "/usr/local/lib/python2.7/dist-packages/twentyc/rpc/client.py", line 117, in get
    return self._load(self._request(typ, id=id, params=kwargs))
No modification madeib/python2.7/dist-packages/twentyc/rpc/client.py", line 88, in _load```

**Comment by bcavns01** [comment]
Hello,

Curious if anyone has had a chance to look at this?

**Comment by grizz** [comment]
@bcavns01 That was from a data issue we think, is it still failing?

I just realized I haven't tagged and released the client 1.0 yet either, so I can do that ASAP to test.

**Comment by arnoldnipper** [comment]
+1 ... please do so

**Comment by bcavns01** [comment]
@grizz   Yes, it looked like a data issue, and it's no longer failing.

**Comment by grizz** [comment]
peeringdb 1.0 has been released.
