### ISSUE TITLE
IX-F Importer: ERROR: 'IXFMemberData' object has no attribute 'ixf_log_entry'

### ISSUE THREAD

**Issue by ccaputo** [peeringdb/peeringdb#859]
The Importer reported the following today.  This may have been related to there being conflicts older than 6 days.

```
ERROR: 'IXFMemberData' object has no attribute 'ixf_log_entry'
Traceback (most recent call last):
  File "/srv/www.peeringdb.com/peeringdb_server/management/commands/pdb_ixf_ixp_member_import.py", line 232, in handle
    success = importer.update(ixlan, save=self.commit, asn=asn)
  File "/srv/www.peeringdb.com/peeringdb_server/ixf.py", line 406, in update
    self.process_saves()
  File "/srv/www.peeringdb.com/venv/lib/python3.7/site-packages/reversion/revisions.py", line 324, in do_revision_context
    return func(*args, **kwargs)
  File "/srv/www.peeringdb.com/peeringdb_server/ixf.py", line 505, in process_saves
    self.apply_add_or_update(ixf_member)
  File "/srv/www.peeringdb.com/peeringdb_server/ixf.py", line 963, in apply_add_or_update
    self.apply_add(ixf_member_data)
  File "/srv/www.peeringdb.com/peeringdb_server/ixf.py", line 1021, in apply_add
    self.consolidate_delete_add(ixf_member_data)
  File "/srv/www.peeringdb.com/peeringdb_server/ixf.py", line 1070, in consolidate_delete_add
    self.log["data"].remove(ip6_deletion.ixf_log_entry)
AttributeError: 'IXFMemberData' object has no attribute 'ixf_log_entry'
```

**Comment by arnoldnipper** [comment]
Routed through to 3a

**Comment by vegu** [comment]
Missed error handling, fixing should be straight forward
