### ISSUE TITLE
IX-F Importer: Intermittent issue with consolidated delete+add

### ISSUE THREAD

**Issue by vegu** [peeringdb/peeringdb#889]
This is another version of the error that was already supposed to be addressed by fixing #859 - this is still happening, albeit elsewhere in the code and needs to be looked at again.

```
ERROR: 'IXFMemberData' object has no attribute 'ixf_log_entry'
Traceback (most recent call last):
  File "/srv/www.peeringdb.com/peeringdb_server/management/commands/pdb_ixf_ixp_member_import.py", line 232, in handle
    success = importer.update(ixlan, save=self.commit, asn=asn)
  File "/srv/www.peeringdb.com/peeringdb_server/ixf.py", line 406, in update
    self.process_saves()
  File "/srv/www.peeringdb.com/venv/lib/python3.7/site-packages/reversion/revisions.py", line 324, in do_revision_context
    return func(*args, **kwargs)
  File "/srv/www.peeringdb.com/peeringdb_server/ixf.py", line 505, in process_saves
    self.apply_add_or_update(ixf_member)
  File "/srv/www.peeringdb.com/peeringdb_server/ixf.py", line 963, in apply_add_or_update
    self.apply_add(ixf_member_data)
  File "/srv/www.peeringdb.com/peeringdb_server/ixf.py", line 1021, in apply_add
    self.consolidate_delete_add(ixf_member_data)
  File "/srv/www.peeringdb.com/peeringdb_server/ixf.py", line 1074, in consolidate_delete_add
    log_entry = ixf_member_data.ixf_log_entry
AttributeError: 'IXFMemberData' object has no attribute 'ixf_log_entry'
```

**Comment by mcmanuss8** [comment]
pushing to 3a, clear bug

**Comment by ccaputo** [comment]
Likely related.  Today got:

```
ERROR: 'IXFMemberData' object has no attribute 'ixf_log_entry'
Traceback (most recent call last):
  File "/srv/www.peeringdb.com/peeringdb_server/management/commands/pdb_ixf_ixp_member_import.py", line 232, in handle
    success = importer.update(ixlan, save=self.commit, asn=asn)
  File "/srv/www.peeringdb.com/peeringdb_server/ixf.py", line 406, in update
    self.process_saves()
  File "/srv/www.peeringdb.com/venv/lib/python3.7/site-packages/reversion/revisions.py", line 324, in do_revision_context
    return func(*args, **kwargs)
  File "/srv/www.peeringdb.com/peeringdb_server/ixf.py", line 505, in process_saves
    self.apply_add_or_update(ixf_member)
  File "/srv/www.peeringdb.com/peeringdb_server/ixf.py", line 963, in apply_add_or_update
    self.apply_add(ixf_member_data)
  File "/srv/www.peeringdb.com/peeringdb_server/ixf.py", line 1021, in apply_add
    self.consolidate_delete_add(ixf_member_data)
  File "/srv/www.peeringdb.com/peeringdb_server/ixf.py", line 1074, in consolidate_delete_add
    log_entry = ixf_member_data.ixf_log_entry
AttributeError: 'IXFMemberData' object has no attribute 'ixf_log_entry'
ERROR: IXFMemberData matching query does not exist.
Traceback (most recent call last):
  File "/srv/www.peeringdb.com/venv/lib/python3.7/site-packages/django/db/models/fields/related_descriptors.py", line 164, in __get__
    rel_obj = self.field.get_cached_value(instance)
  File "/srv/www.peeringdb.com/venv/lib/python3.7/site-packages/django/db/models/fields/mixins.py", line 13, in get_cached_value
    return instance._state.fields_cache[cache_name]
KeyError: 'requirement_of'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/www.peeringdb.com/peeringdb_server/management/commands/pdb_ixf_ixp_member_import.py", line 232, in handle
    success = importer.update(ixlan, save=self.commit, asn=asn)
  File "/srv/www.peeringdb.com/peeringdb_server/ixf.py", line 408, in update
    self.cleanup_ixf_member_data()
  File "/srv/www.peeringdb.com/peeringdb_server/ixf.py", line 596, in cleanup_ixf_member_data
    ixf_member.set_resolved(save=self.save)
  File "/srv/www.peeringdb.com/peeringdb_server/models.py", line 3252, in set_resolved
    if self.id and save and not self.requirement_of:
  File "/srv/www.peeringdb.com/venv/lib/python3.7/site-packages/django/db/models/fields/related_descriptors.py", line 178, in __get__
    rel_obj = self.get_object(instance)
  File "/srv/www.peeringdb.com/venv/lib/python3.7/site-packages/django/db/models/fields/related_descriptors.py", line 145, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
  File "/srv/www.peeringdb.com/venv/lib/python3.7/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
peeringdb_server.models.IXFMemberData.DoesNotExist: IXFMemberData matching query does not exist.
```

**Comment by ccaputo** [comment]
@vegu, @arnoldnipper, and myself discussed via email and came up with:

**Summary:**

When there multiple JSON VLANs for one ixlan.ixpfx_set[] this should cause the import to fail and dispatch an error notification email to the exchange.
